services: 
  kafka:
    image: bitinit/kafka:latest
    restart: on-failture
    ports:
      - "9092:9092"
    environment:     
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEPPER_CONNENECT: zookeeper:2181
      KAFKA_CFG_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    restart: always



  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    
    ports:
      - "8080:8080"
    restart: always
  
  producer:
    container_name: producer
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
    - kafka



      

  
    



